# 指定运行程序  c : client s: server
run: c
# 公网服务器端口
server_port: 7777
# 客户端链接公网服务器的端口 必须和server_port一致
client_connect_port: 7777
# 公网服务器监听端口
server_binds:
  - id: '1'
    port: 3346
  # 如需监听多个 下面继续写
  - id: '2'
    port: 3357

# 内网服务器访问公网的端口
client_connect_addr: '192.168.1.3'
# 内网监听的端口
client_proxys:
  - id: '1'
    proxy_addr: '192.168.1.3'
    proxy_port: 9999
  - id: '2'
    proxy_addr: '192.168.1.3'
    proxy_port: 6666
